#theme: jekyll-theme-minimal

title: Teaching
email:
description: >- # this means to ignore newlines until "baseurl:"
  This is a sort of blog where I attempt to teach people some things. No promises.
# twitter_username: username
github_username: Pyxxil

remote_theme: "mmistakes/minimal-mistakes@4.16.6"

permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Pacific/Auckland # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

minimal_mistakes_skin: dark
search: true

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Josh Hill"
  #avatar : "/assets/images/bio-photo.jpg"
  bio    : "This is where I try my best to teach people things. Hopefully."
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Pyxxil"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Pyxxil"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
